name: Generate Sitemap

on:
  push:
    branches:
      - main # or 'master' depending on your repo

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://trevorcommons.github.io
          # include project folder in sitemap
          include-paths: /
          # optional: exclude non-page assets like JS/CSS/images
          exclude-paths: /js /css /images
